server.port=8082

spring.application.name=LuckyTavern
spring.security.user.name=admin
spring.security.user.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5432/casino
spring.datasource.password=admin
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

jwt.secret=MegaSuperDuperInsaneJWTTokenSecretMegaSuperDuperInsaneJWTTokenSecret
jwt.lifetime=3600000000

spring.main.allow-circular-references=true